#!/bin/bash
# Simple local P2P test - NO RELAY NEEDED
# This tests direct P2P connections on localhost

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Spaceway - Direct P2P Test (No Relay Required!)          ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}✅ Testing direct P2P connections on localhost${NC}"
echo -e "${GREEN}✅ No relay server needed for this test!${NC}"
echo ""
echo -e "${YELLOW}📋 What this tests:${NC}"
echo "  • Direct peer-to-peer connections"
echo "  • GossipSub messaging"
echo "  • Kademlia DHT storage"
echo "  • CRDT synchronization"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}Step 1: Open 3 terminal windows${NC}"
echo ""
echo -e "${GREEN}Terminal 1 (Alice):${NC}"
echo "  cd $(pwd)"
echo "  ./run-spaceway.sh --account ./alice.key --port 9001"
echo ""
echo -e "${GREEN}Terminal 2 (Bob):${NC}"
echo "  cd $(pwd)"
echo "  ./run-spaceway.sh --account ./bob.key --port 9002"
echo ""
echo -e "${GREEN}Terminal 3 (Charlie):${NC}"
echo "  cd $(pwd)"
echo "  ./run-spaceway.sh --account ./charlie.key --port 9003"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}Step 2: Wait for all to start (10 seconds)${NC}"
echo ""
echo "You'll see: ✓ Generated 10 KeyPackages"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}Step 3: Connect peers (run in each terminal)${NC}"
echo ""
echo -e "${GREEN}In Bob's terminal:${NC}"
echo "  connect /ip4/127.0.0.1/tcp/9001"
echo "  network    (should see 2 peers)"
echo ""
echo -e "${GREEN}In Charlie's terminal:${NC}"
echo "  connect /ip4/127.0.0.1/tcp/9001"
echo "  network    (should see 2 peers)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}Step 4: Create space (in Alice's terminal)${NC}"
echo ""
echo "  space create \"TestSpace\""
echo "  channel create \"general\""
echo "  thread create \"Hello\""
echo "  invite create"
echo ""
echo -e "${CYAN}📝 Copy the space ID and invite code!${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}Step 5: Bob and Charlie join${NC}"
echo ""
echo -e "${GREEN}In Bob's terminal:${NC}"
echo "  join <space_id> <invite_code>"
echo "  space <space_id>"
echo "  send \"Hi from Bob!\""
echo ""
echo -e "${GREEN}In Charlie's terminal:${NC}"
echo "  join <space_id> <invite_code>"
echo "  space <space_id>"
echo "  send \"Hi from Charlie!\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}✅ That's it! You're testing P2P without any relay server!${NC}"
echo ""
echo -e "${CYAN}📚 For more info, read: NETWORK_ARCHITECTURE_EXPLAINED.md${NC}"
echo ""
